### ISSUE TITLE
Post form data?

### ISSUE THREAD

**Issue by indrekru** [timmckenzie/har-server#1]
Hey,

I've been using it and ran into some trouble.
I have multiple responses on the same URL. What I'm missing is the feature to compare POST form data. 

I know it's written strictly in the spec that it doesn't do that... but I'm just asking if there are any plans on adding this?
Or any alternative har-server's out there that do that?
Another idea I could write a pull request for that, but I would need some pointers first.

EDIT: Started debugging it, where's the POST form data, can't see it anywhere in the request object?

EDIT: Hacked around a bit, in my use case I injected the post data to headers and on the har-server side I changed the harServer.js to check if entry has request post params and see if they match with the ones from the request headers. This works for me for now.. Any thoughts?

Thanks

**Comment by timmckenzie** [comment]
I think it is a good idea to match on POST/PUT bodies.  

Also sorry for the late reply, I must have missed the email/notification.

**Comment by timmckenzie** [comment]
I just pushed version 0.4.2 to NPM.  It now checks the request body against the HAR file's request body.
